config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :chat_rooms, only: [:index] do
    resources :messages, only: [:create]
  end

  resources :invites, only: %i[create index destroy] do
    member do
      put 'accept'
      put 'decline'
    end
  end

  root 'chat_rooms#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
# frozen_string_literal: true

class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users

  validates :room_type, inclusion: { in: %w[group direct] }
end

app/models/chat_room_user.rb
# frozen_string_literal: true

class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :chat_room_id, presence: true
  validates :user_id, presence: true
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'


  validates :status, inclusion: { in: %w[pending accepted declined] }

  scope :pending, -> { where(status: 'pending') }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :content, presence: true
  after_create :send_notification_to_user

  def send_notification_to_user
    other_user = chat_room.users.where.not(id: user.id).first
    return unless other_user

    unread_count = chat_room.messages.where(read: false, user_id: user.id).count
    Rails.logger.info "Enviando notificação para o usuário #{other_user.id} com o número de mensagens não lidas #{unread_count}"
    NotificationsChannel.broadcast_to(other_user, {
                                        chat_room_id: chat_room.id,
                                        unread_count: unread_count,
                                        user_id: user.id,
                                        message: self
                                      })
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :messages
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :sent_invites, class_name: 'Invite', foreign_key: 'sender_id'
  has_many :received_invites, class_name: 'Invite', foreign_key: 'receiver_id'
  before_create :generate_unique_hash

  validates_uniqueness_of :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def generate_unique_hash
    self.invite_code = loop do
      hash = SecureRandom.hex(10)
      break hash unless User.exists?(invite_code: hash)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
# frozen_string_literal: true

class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = current_user.chat_rooms.includes(:users, :messages).joins(:users)
    @current_user = current_user
    @unread = @chat_rooms.each_with_object({}) do |chat_room, counts|
      counts[chat_room.id] = chat_room.messages.where(read: false).where.not(user_id: current_user.id).count
    end
    @selected_chat = if params[:chat_room_id].present?
                       @chat_rooms.find_by(id: params[:chat_room_id])
                     else
                       @chat_rooms.first
                     end
    if @selected_chat
      @selected_chat.messages.where(read: false).where.not(user_id: current_user.id).update_all(read: true)
    else
      redirect_to root_path and return
    end
  end
end

app/controllers/invites_controller.rb
# frozen_string_literal: true

class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :accept, :decline]

  def index
    @received_invites = current_user.received_invites.pending
    @sent_invites = current_user.sent_invites
  end

  def create
    receiver = User.find_by(invite_code: params[:invite_code])

    if receiver.nil?
      flash[:alert] = "Usuário não encontrado. Verifique o código e tente novamente."
      redirect_to invites_path and return
    end

    if Invite.exists?(sender_id: current_user.id, receiver_id: receiver.id)
      flash[:alert] = "Você já enviou um convite para este usuário."
    else
      Invite.create(sender_id: current_user.id, receiver_id: receiver.id, status: "pending")
      flash[:notice] = "Convite enviado com sucesso!"
    end

    redirect_to invites_path
  end

  def accept
    @invite = Invite.find(params[:id])
    @invite.update(status: 'accepted')

    sender_id = User.find(@invite.sender_id)
    receiver_invite = User.find(@invite.receiver_id)

    chat = ChatRoom.create(room_type: 'direct')
    chat.users << sender_id unless chat.users.include?(sender_id)
    chat.users << receiver_invite unless chat.users.include?(receiver_invite)

    redirect_to root_path
  end

  def decline
    @invite = Invite.find(params[:id])
    @invite.update(status: 'rejected')
    redirect_to user_path(current_user)
  end

  private

  def invite_params
    params.require(:invite).permit(:sender_id, :receiver_id, :status)
  end

  def set_invite
    @invite = Invite.find(params[:id])
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_chat_room

  def create
    @message = @chat_room.messages.new(message_params)
    @message.user = current_user

    if @message.save
      MessagesOfChatChannel.broadcast_to(@chat_room.id, message: @message)
    else
      Rails.logger.info 'Não foi possível enviar a mensagem.'
    end
  end

  private

  def set_chat_room
    @chat_room = current_user.chat_rooms.find_by(id: params[:chat_room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
# frozen_string_literal: true

module ChatRoomsHelper
end

app/helpers/invites_helper.rb
# frozen_string_literal: true

module InvitesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/views/chat_rooms/_chat.html.slim
div(class="flex flex-col h-[calc(92vh-4rem)] border-l-[1px] border-black/20")
  div(class="flex-grow p-4 space-y-4 overflow-y-auto" id="chat" data-chat-room-id=chat.id data-user-id=current_user.id)
    - last_date = nil
    - if chat.messages.any?
      - chat.messages.each do |message|
        - current_date = message.created_at.to_date
        - if current_date != last_date
          - if current_date == Date.today
            div(class="flex justify-center my-4")
              span(class="bg-gray-100 text-gray-500 text-xs px-2 py-1 rounded-md") Hoje
          - elsif current_date == Date.yesterday
            div(class="flex justify-center my-4")
              span(class="bg-gray-100 text-gray-500 text-xs px-2 py-1 rounded-md") Ontem
          - else
            div(class="flex justify-center my-4")
              span(class="bg-gray-100 text-gray-500 text-xs px-2 py-1 rounded-md") #{current_date.strftime("%d/%m")}
          - last_date = current_date
        = render partial: "messages/message", locals: { message: message, current_user: current_user }
    - else
      div(class="flex justify-center my-4")
        span(class="bg-gray-100 text-gray-500 text-xs px-2 py-1 rounded-md") Nenhuma mensagem
  div(class="p-4 border-t-[1px] border-black/15")
    = form_with(model: Message.new, url: chat_room_messages_path(chat), method: :post, local: true, class: "flex flex-row space-x-2", id: "message-form") do |f|
      = f.text_field :content, placeholder: "Escreva uma mensagem...", class: "w-full rounded-lg p-2 border border-gray-300 focus:border-blue-500", id: "message-input"
      = f.submit "Enviar", class: "bg-blue-500 text-white rounded-lg px-4 py-2 hover:bg-blue-600"
javascript:
  function initializeChat() {
    const chatElement = document.getElementById("chat");
    const form = document.getElementById("message-form");
    const input = document.getElementById("message-input");

    if (form && input) {
      input.addEventListener("keypress", (event) => {
        if (event.key === "Enter" && !event.shiftKey) {
          event.preventDefault();
          form.submit();
          input.value = "";
        }
      });

      form.addEventListener("submit", (event) => {
        if (!input.value) {
          event.preventDefault();
        } else {
          event.preventDefault();
          form.submit();
          input.value = "";
        }
      });
    }

    if (chatElement) {
      chatElement.scrollTop = chatElement.scrollHeight;
    }
  }

  initializeChat();

app/views/chat_rooms/_list.html.slim
- i = 0

ul(class="h-full w-60 border-r bg-white overflow-y-auto")
  - chats.each do |chat|
    - other_user = chat.users.where.not(id: current_user.id).first
    - last_message = chat.messages.order(created_at: :desc).first
    - last_date = nil
    = link_to chat_rooms_path(chat_room_id: chat.id), remote: true, class: "text-blue-500 " do
      button(class="flex w-full justify-between p-2 items-center hover:bg-blue-100 transition-colors #{'bg-blue-200' if selected_chat == chat}" id="chat-button-#{i}")
        div(class="flex flex-col items-start gap-1 bottom-0 h-full" id="last-message" data-chat-room-id=chat.id)
          = other_user.name
          - if last_message
            p(class="text-xs text-gray-500") = last_message.content
          - else
            p(class="text-xs text-gray-500") Nenhuma mensagem
        - if last_message
          div(class="flex flex-col")
            - if last_message.created_at.to_date == Date.today
              span(class="text-xs text-gray-500") #{last_message.created_at.strftime("%H:%M")}
            - elsif last_message.created_at.to_date == Date.yesterday
              span(class="text-xs text-gray-500") Ontem
            - else
              span(class="text-xs text-gray-500") #{last_message.created_at.strftime("%d/%m")}
            - unread = @unread[chat.id]
            div(id="unread-badge" data-chat-room-id=chat.id data-user-id=current_user.id)
              - if unread > 0
                span(class="bg-blue-500 text-white rounded-full p-[6px] text-xs") #{unread}
    - i += 1

app/views/chat_rooms/index.html.slim
section(class="flex w-full h-full")
  = render "list", chats: @chat_rooms, selected_chat: @selected_chat, unread: @unread
  div(class="flex-grow")
    - if @selected_chat
      div(class="bg-gray-100 p-4 border-b")
        - other_user = @selected_chat.users.where.not(id: @current_user.id).first
        h1(class="text-black font-sans text-sm justify-end flex") #{@selected_chat.name || other_user.name }
      = render "chat", chat: @selected_chat, current_user: @current_user
    - else
      div(class="bg-gray-100 p-4 border-b")
        h1 Selecione um chat para começar a conversa

app/views/invites/index.html.slim
h1.text-2xl.font-bold.text-white Convites

h2.text-xl.font-semibold.text-gray-200 Meu Código de Convite
div(class="flex flex-row gap-2")
    p.bg-gray-800.text-black.rounded-lg.font-mono.w-fit.mb-6.py-2(id="invite-code")
        = current_user.invite_code
    button(class=" text-black p-2 rounded-lg bg-slate-400" onClick="copyToClipboard()") 
        i(class="fa-solid fa-copy")

= form_with url: invites_path, method: :post, class: "flex flex-col gap-2" do |f|
  = f.label :invite_code, "Insira o código único do usuário:", class: "text-black"
  = f.text_field :invite_code, class: "p-2 rounded-lg border border-gray-500 w-1/2", placeholder: "Código de Convite"
  = f.submit "Enviar Convite", class: "bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition"

h2.text-xl.font-semibold.text-gray-200 Recebidos
- if @received_invites.any?
  ul
    - @received_invites.each do |invite|
      li(class="bg-gray-800 text-black p-4 rounded-lg mb-4 flex justify-between items-center")
        = invite.sender.name
        = link_to "Aceitar", accept_invite_path(invite.id), data: { turbo_method: :put }, class: "bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600 transition"
        = link_to "Recusar", decline_invite_path(invite.id), data: { turbo_method: :put }, class: "bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 transition"
- else
  p.text-gray-400 Nenhum convite recebido.

h2.text-xl.font-semibold.text-gray-200 Enviados
- if @sent_invites.any?
  ul
    - @sent_invites.each do |invite|
      li(class="bg-gray-800 text-black p-4 rounded-lg mb-4")
        | Convite enviado para: 
        = invite.receiver.name
- else
  p.text-gray-400 Você ainda não enviou convites.

javascript:
    function copyToClipboard() {
        input = document.getElementById("invite-code").textContent;
        navigator.clipboard.writeText(input).then(function() {
            console.log("Copiado!");
        }).catch(function(err) {
            console.log("Falha ao copiar!" + err);
        });
    }

app/views/layouts/_header.html.slim
header
  nav(class="flex flex-row items-center justify-between w-full h-16 bg-slate-800 px-8")
    = link_to "Chat Application", root_path, class: "text-white font-semibold"
    div(class="flex items-center justify-end")
      - if user_signed_in?
          = link_to chat_rooms_path, class: "bg-blue-500 gap-2 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition flex items-center" do
            i(class="fa-solid fa-comments")
            | Chats
          = link_to invites_path, class: "ml-4 bg-blue-500 gap-2 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition flex items-center" do
            i(class="fa-solid fa-envelope")
            | Convites
          = link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "ml-4 bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 transition gap-2 flex items-center" do 
            i(class="fa-solid fa-arrow-right-from-bracket ")
            | Sair

app/views/layouts/application.html.slim
doctype html
html lang="pt-BR"
  head
    title
      | Buggy
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    main
      - if user_signed_in?
        = render "layouts/header"
      = yield

app/views/messages/_message.html.slim
div(class="flex items-start space-x-2 #{message.user_id === current_user.id ? 'justify-end' : ''}")
    div(class="rounded-lg p-2 max-w-[70%] #{message.user_id === current_user.id ? 'bg-blue-500 text-white' : 'bg-gray-100'}")
        p(class="text-sm") #{message.content}
        p(class="text-xs items-start flex #{message.user_id === current_user.id ? 'text-blue-100 justify-end' : 'text-gray-500'} mt-1") #{message.created_at.strftime("%H:%M")}